name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # Text-to-speech
  flutter_tts: ^4.0.2
  # Audio player pour ambiances sonores
  just_audio: ^0.9.36
  # Stockage local pour préférences
  shared_preferences: ^2.2.3
  # VoIP (simulation)
  agora_rtc_engine: ^6.4.0
  permission_handler: ^11.0.1
  # URL launcher pour appels téléphoniques
  url_launcher: ^6.2.3
  # Notifications - using newer compatible version
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    # Pour les sons d'ambiance (à ajouter dans les assets du projet)
    - assets/audio/ocean.mp3
    - assets/audio/forest.mp3
    - assets/audio/rain.mp3
    - assets/audio/birds.mp3
